// CSV column names from the broker export
const CSV_COLS = {
  timestamp: 'Entry Timestamp',
  direction: 'Buy/Sell',   // values: 'Buy' or 'Sell'
  volume:    'Volume',
  product:   'Product',
  price:     'Price',
  account:   'Account',
};

// Strips contract month suffix e.g. "ICE LS Gasoil JUN26" -> "ICE LS Gasoil"
function stripContractMonth(product) {
  return product.replace(/\s+(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\d{2}$/i, '').trim();
}

// Contract specs: multiplier = point_value (currency units per 1-point move per lot)
// P&L = (exit - entry) × contracts × multiplier   [long; negate for short]
const CONTRACT_SPECS = {

  // ── CME Equity Index ──────────────────────────────────────────────────────
  'S&P500 Micro':               { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },
  'S&P 500 Micro':              { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },
  'MINI-S&P500 EQUAL':          { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MINI-S&P500 ESG':            { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MINI-S&P500':                { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'CME E-mini S&P 500':         { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'CME Micro E-mini S&P':       { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },
  'NASDAQ100 Micro':            { currency: 'USD', multiplier: 2,      assetClass: 'Equity Index' },
  'MINI-NAS':                   { currency: 'USD', multiplier: 20,     assetClass: 'Equity Index' },
  'MINI-NASDAQ100':             { currency: 'USD', multiplier: 20,     assetClass: 'Equity Index' },
  'CME E-mini Nasdaq-100':      { currency: 'USD', multiplier: 20,     assetClass: 'Equity Index' },
  'CME Micro E-mini Nasdaq':    { currency: 'USD', multiplier: 2,      assetClass: 'Equity Index' },
  'DOW Micro':                  { currency: 'USD', multiplier: 0.5,    assetClass: 'Equity Index' },
  'MINI-DOW':                   { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },
  'CME E-mini Dow':             { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },
  'RUSSELL2000 Micro':          { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },
  'E-MINI RUSSELL 1000 Growth': { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'E-MINI RUSSELL 1000 Value':  { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'E-MINI RUSSELL 1000':        { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'E-MINI RUSSELL':             { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'CME E-mini Russell 2000':    { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'E-MINI S&P MIDCAP':          { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },

  // ── COMEX Metals ──────────────────────────────────────────────────────────
  'E-MICRO COMEX Gold':         { currency: 'USD', multiplier: 10,     assetClass: 'Metals' },
  'COMEX Gold Enhanced':        { currency: 'USD', multiplier: 100,    assetClass: 'Metals' },
  'COMEX Gold 1oz':             { currency: 'USD', multiplier: 1,      assetClass: 'Metals' },
  'COMEX miNY Gold':            { currency: 'USD', multiplier: 33.2,   assetClass: 'Metals' },
  'COMEX Gold':                 { currency: 'USD', multiplier: 100,    assetClass: 'Metals' },
  'E-MICRO COMEX Copper':       { currency: 'USD', multiplier: 2500,   assetClass: 'Metals' },
  'EMINI Copper':               { currency: 'USD', multiplier: 12500,  assetClass: 'Metals' },
  'COMEX Copper':               { currency: 'USD', multiplier: 25000,  assetClass: 'Metals' },
  'COMEX 1000oz Silver':        { currency: 'USD', multiplier: 1000,   assetClass: 'Metals' },
  'E-MICRO COMEX Silver':       { currency: 'USD', multiplier: 500,    assetClass: 'Metals' },
  'COMEX miNY Silver':          { currency: 'USD', multiplier: 2500,   assetClass: 'Metals' },
  'COMEX Silver':               { currency: 'USD', multiplier: 5000,   assetClass: 'Metals' },
  'Platinum':                   { currency: 'USD', multiplier: 50,     assetClass: 'Metals' },
  'Palladium':                  { currency: 'USD', multiplier: 100,    assetClass: 'Metals' },
  'COMEX Aluminum':             { currency: 'USD', multiplier: 25,     assetClass: 'Metals' },
  'COMEX Zinc':                 { currency: 'USD', multiplier: 25,     assetClass: 'Metals' },
  'COMEX Cobalt':               { currency: 'USD', multiplier: 1000,   assetClass: 'Metals' },
  'COMEX Lithium':              { currency: 'USD', multiplier: 100,    assetClass: 'Metals' },

  // ── Energy – NYMEX / CME ──────────────────────────────────────────────────
  'Light Sweet Crude Oil Micro': { currency: 'USD', multiplier: 100,   assetClass: 'Energy' },
  'MCL':                         { currency: 'USD', multiplier: 100,   assetClass: 'Energy' },
  'Light Sweet Crude':           { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'Micro Crude':                 { currency: 'USD', multiplier: 100,   assetClass: 'Energy' },
  'MINY Light Sweet':            { currency: 'USD', multiplier: 500,   assetClass: 'Energy' },
  'NYMEX Crude Oil':             { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'NYMEX WTI':                   { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'Natural Gas Micro':           { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'MNG':                         { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'MINY Natural Gas':            { currency: 'USD', multiplier: 2500,  assetClass: 'Energy' },
  'Natural Gas':                 { currency: 'USD', multiplier: 10000, assetClass: 'Energy' },
  'NYMEX Natural Gas':           { currency: 'USD', multiplier: 10000, assetClass: 'Energy' },
  'Heating Oil':                 { currency: 'USD', multiplier: 42000, assetClass: 'Energy' },
  'NYMEX Heating Oil':           { currency: 'USD', multiplier: 42000, assetClass: 'Energy' },
  'RBOB Gasoline':               { currency: 'USD', multiplier: 42000, assetClass: 'Energy' },
  'NYMEX RBOB Gasoline':         { currency: 'USD', multiplier: 42000, assetClass: 'Energy' },
  'Brent Crude Oil Last Day':    { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'Brent Crude':                 { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'Chicago Ethanol':             { currency: 'USD', multiplier: 29000, assetClass: 'Energy' },

  // ── Energy – ICE ──────────────────────────────────────────────────────────
  'ICE LS Gasoil':              { currency: 'USD', multiplier: 100,   assetClass: 'Energy' },
  'ICE Gas Oil':                { currency: 'USD', multiplier: 100,   assetClass: 'Energy' },
  'ICE Low Sulphur Gasoil':     { currency: 'USD', multiplier: 100,   assetClass: 'Energy' },
  'ICE Brent Crude':            { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'ICE WTI Crude':              { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'ICE Heating Oil':            { currency: 'USD', multiplier: 42000, assetClass: 'Energy' },
  'ICE RBOB Gasoline':          { currency: 'USD', multiplier: 42000, assetClass: 'Energy' },
  'ICE Natural Gas':            { currency: 'USD', multiplier: 10000, assetClass: 'Energy' },
  'Dutch TTF':                  { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'UK NBP Nat Gas':             { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'ICE Murban Crude':           { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'ICE Midland WTI':            { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'ICE Permian WTI':            { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'ICE Dubai':                  { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'Newcastle Coal':             { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'Rotterdam Coal':             { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'ICE ECX':                    { currency: 'EUR', multiplier: 1000,  assetClass: 'Energy' },
  'ICE UKA':                    { currency: 'GBP', multiplier: 1000,  assetClass: 'Energy' },
  'ICE SG Mini WTI':            { currency: 'USD', multiplier: 500,   assetClass: 'Energy' },
  'ICE SG Mini USD':            { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'ICE German NCG':             { currency: 'EUR', multiplier: 1000,  assetClass: 'Energy' },
  'ICE Italian PSV':            { currency: 'EUR', multiplier: 1000,  assetClass: 'Energy' },
  'ICE Dutch Power':            { currency: 'EUR', multiplier: 720,   assetClass: 'Energy' },
  'ICE German Power':           { currency: 'EUR', multiplier: 720,   assetClass: 'Energy' },
  'ICE Italian Power':          { currency: 'EUR', multiplier: 720,   assetClass: 'Energy' },
  'Naphtha Calendar':           { currency: 'USD', multiplier: 10000, assetClass: 'Energy' },
  'Coal CIF ARA':               { currency: 'USD', multiplier: 1000,  assetClass: 'Energy' },
  'HRC':                        { currency: 'USD', multiplier: 20,    assetClass: 'Energy' },
  'US Midwest HRC':             { currency: 'USD', multiplier: 20,    assetClass: 'Energy' },
  'Crude Palm Oil':             { currency: 'MYR', multiplier: 25,    assetClass: 'Energy' },
  'BMD Palm':                   { currency: 'MYR', multiplier: 25,    assetClass: 'Energy' },

  // ── Treasury Futures ──────────────────────────────────────────────────────
  'ULTRA-10YR-TNOTE Micro':     { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  'ULTRA-10YR-TNOTE':           { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  'ULTRA-TBOND Micro':          { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  'ULTRA-TBOND':                { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '10YR Micro Treasury':        { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '10YR-TNOTE':                 { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '10-Year T-Note':             { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  'CBOT 10-Year T-Note':        { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '20YR-TBOND':                 { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '30YR Micro Treasury':        { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '30YR-TBOND':                 { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '30-Year T-Bond':             { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  'CBOT 30-Year T-Bond':        { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '5YR Micro Treasury':         { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '5YR-TNOTE':                  { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '2YR Micro Treasury':         { currency: 'USD', multiplier: 1000,  assetClass: 'Rates' },
  '2YR-TNOTE':                  { currency: 'USD', multiplier: 2000,  assetClass: 'Rates' },
  '3YR-TNOTE':                  { currency: 'USD', multiplier: 2000,  assetClass: 'Rates' },
  '13-Week T-Bill':             { currency: 'USD', multiplier: 2500,  assetClass: 'Rates' },
  '30DayFedFunds':              { currency: 'USD', multiplier: 4166.67, assetClass: 'Rates' },
  '3 Month SOFR':               { currency: 'USD', multiplier: 2500,  assetClass: 'Rates' },
  '1 Month SOFR':               { currency: 'USD', multiplier: 4166.67, assetClass: 'Rates' },
  'EURODOLLAR':                 { currency: 'USD', multiplier: 2500,  assetClass: 'Rates' },
  'CME Eurodollar':             { currency: 'USD', multiplier: 2500,  assetClass: 'Rates' },
  'EURIBOR':                    { currency: 'EUR', multiplier: 2500,  assetClass: 'Rates' },
  'Euribor':                    { currency: 'EUR', multiplier: 2500,  assetClass: 'Rates' },
  'SONIA THREE MONTH':          { currency: 'GBP', multiplier: 2500,  assetClass: 'Rates' },
  'ICE Short Sterling':         { currency: 'GBP', multiplier: 2500,  assetClass: 'Rates' },
  'ICE 1 Month SOFR':           { currency: 'USD', multiplier: 4166.67, assetClass: 'Rates' },
  'ICE 3 Month SOFR':           { currency: 'USD', multiplier: 2500,  assetClass: 'Rates' },
  'Three Month ESTR':           { currency: 'EUR', multiplier: 2500,  assetClass: 'Rates' },
  'ESTR':                       { currency: 'EUR', multiplier: 2500,  assetClass: 'Rates' },
  'MPC Dated SONIA':            { currency: 'GBP', multiplier: 2500,  assetClass: 'Rates' },
  'ECB Dated ESTR':             { currency: 'EUR', multiplier: 2500,  assetClass: 'Rates' },
  'ICE 3 MONTH SARON':          { currency: 'CHF', multiplier: 2500,  assetClass: 'Rates' },
  'SARON':                      { currency: 'CHF', multiplier: 2500,  assetClass: 'Rates' },
  'LR':                         { currency: 'GBP', multiplier: 1000,  assetClass: 'Rates' },

  // ── FX Futures – CME ──────────────────────────────────────────────────────
  'E-MICRO EUR/USD':            { currency: 'USD', multiplier: 12500,    assetClass: 'FX' },
  'E-MINI EURO-FX':             { currency: 'USD', multiplier: 62500,    assetClass: 'FX' },
  'EURO-FX':                    { currency: 'USD', multiplier: 125000,   assetClass: 'FX' },
  'Euro FX':                    { currency: 'USD', multiplier: 125000,   assetClass: 'FX' },
  'CME Euro FX':                { currency: 'USD', multiplier: 125000,   assetClass: 'FX' },
  'E-MICRO GBP/USD':            { currency: 'USD', multiplier: 6250,     assetClass: 'FX' },
  'GBP/CHF':                    { currency: 'USD', multiplier: 62500,    assetClass: 'FX' },
  'GBP/JPY':                    { currency: 'USD', multiplier: 625,      assetClass: 'FX' },
  'GBP':                        { currency: 'USD', multiplier: 62500,    assetClass: 'FX' },
  'CME British Pound':          { currency: 'USD', multiplier: 62500,    assetClass: 'FX' },
  'E-MICRO JPY/USD':            { currency: 'USD', multiplier: 1250000,  assetClass: 'FX' },
  'E-MINI JPY':                 { currency: 'USD', multiplier: 6250000,  assetClass: 'FX' },
  'JPY':                        { currency: 'USD', multiplier: 12500000, assetClass: 'FX' },
  'CME Japanese Yen':           { currency: 'USD', multiplier: 12500000, assetClass: 'FX' },
  'E-MICRO AUS/USD':            { currency: 'USD', multiplier: 10000,    assetClass: 'FX' },
  'AUD/JPY':                    { currency: 'USD', multiplier: 1000,     assetClass: 'FX' },
  'AUD/NZD':                    { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'AUD/CAD':                    { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'AUD':                        { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'CME Australian Dollar':      { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'E-MICRO CAD/USD':            { currency: 'USD', multiplier: 10000,    assetClass: 'FX' },
  'CAD/JPY':                    { currency: 'USD', multiplier: 1000,     assetClass: 'FX' },
  'CAD':                        { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'CME Canadian Dollar':        { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'E-MICRO CHF/USD':            { currency: 'USD', multiplier: 12500,    assetClass: 'FX' },
  'CHF/JPY':                    { currency: 'USD', multiplier: 1250,     assetClass: 'FX' },
  'CHF':                        { currency: 'USD', multiplier: 125000,   assetClass: 'FX' },
  'CME Swiss Franc':            { currency: 'USD', multiplier: 125000,   assetClass: 'FX' },
  'NZD':                        { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'MXN':                        { currency: 'USD', multiplier: 500000,   assetClass: 'FX' },
  'BRL':                        { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'USD/RMB':                    { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'RENMINBI':                   { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'USD/CNH':                    { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'CNH':                        { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },
  'EURO/CHF':                   { currency: 'USD', multiplier: 125000,   assetClass: 'FX' },
  'EURO/GBP':                   { currency: 'USD', multiplier: 62500,    assetClass: 'FX' },
  'EURO/JPY':                   { currency: 'USD', multiplier: 625,      assetClass: 'FX' },
  'NYBOT US Dollar Index':      { currency: 'USD', multiplier: 1000,     assetClass: 'FX' },
  'E-Micro Indian Rupee':       { currency: 'USD', multiplier: 1000000,  assetClass: 'FX' },
  'Micro INR':                  { currency: 'USD', multiplier: 1000000,  assetClass: 'FX' },
  'Indian Rupee':               { currency: 'USD', multiplier: 5000000,  assetClass: 'FX' },
  'Norwegian Krone':            { currency: 'USD', multiplier: 200000,   assetClass: 'FX' },
  'Swedish Krona':              { currency: 'USD', multiplier: 200000,   assetClass: 'FX' },
  'South African Rand':         { currency: 'USD', multiplier: 500000,   assetClass: 'FX' },
  'Korean Won':                 { currency: 'USD', multiplier: 25000,    assetClass: 'FX' },
  'Israeli Shekel':             { currency: 'USD', multiplier: 100000,   assetClass: 'FX' },

  // ── Crypto ────────────────────────────────────────────────────────────────
  'CME Bitcoin Micro':          { currency: 'USD', multiplier: 0.1,    assetClass: 'Crypto' },
  'Bitcoin Micro':              { currency: 'USD', multiplier: 0.1,    assetClass: 'Crypto' },
  'CME Bitcoin Friday':         { currency: 'USD', multiplier: 0.1,    assetClass: 'Crypto' },
  'CME Bitcoin':                { currency: 'USD', multiplier: 5,      assetClass: 'Crypto' },
  'Ether Micro':                { currency: 'USD', multiplier: 0.1,    assetClass: 'Crypto' },
  'Ether Futures':              { currency: 'USD', multiplier: 50,     assetClass: 'Crypto' },
  'Ether':                      { currency: 'USD', multiplier: 50,     assetClass: 'Crypto' },
  'CME Solana Micro':           { currency: 'USD', multiplier: 25,     assetClass: 'Crypto' },
  'CME Solana':                 { currency: 'USD', multiplier: 500,    assetClass: 'Crypto' },
  'CME XRP Micro':              { currency: 'USD', multiplier: 25000,  assetClass: 'Crypto' },
  'CME XRP':                    { currency: 'USD', multiplier: 500000, assetClass: 'Crypto' },
  'Spot-Quoted Bitcoin':        { currency: 'USD', multiplier: 5,      assetClass: 'Crypto' },
  'Spot-Quoted Ether':          { currency: 'USD', multiplier: 50,     assetClass: 'Crypto' },
  'Spot-Quoted Nasdaq':         { currency: 'USD', multiplier: 20,     assetClass: 'Equity Index' },
  'Spot-Quoted Russell':        { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'Spot-Quoted S&P':            { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'Spot-Quoted Dow':            { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },

  // ── Grains & Agriculture ──────────────────────────────────────────────────
  'Corn Micro':                 { currency: 'USD', multiplier: 10,     assetClass: 'Agriculture' },
  'Mini-Corn':                  { currency: 'USD', multiplier: 10,     assetClass: 'Agriculture' },
  'Corn':                       { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'CBOT Corn':                  { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'Soybeans Micro':             { currency: 'USD', multiplier: 10,     assetClass: 'Agriculture' },
  'Mini-Soybeans':              { currency: 'USD', multiplier: 10,     assetClass: 'Agriculture' },
  'Soybeans':                   { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'CBOT Soybeans':              { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'SoybeanMeal Micro':          { currency: 'USD', multiplier: 10,     assetClass: 'Agriculture' },
  'SoybeanMeal':                { currency: 'USD', multiplier: 100,    assetClass: 'Agriculture' },
  'CBOT Soybean Meal':          { currency: 'USD', multiplier: 100,    assetClass: 'Agriculture' },
  'SoybeanOil Micro':           { currency: 'USD', multiplier: 60,     assetClass: 'Agriculture' },
  'SoybeanOil':                 { currency: 'USD', multiplier: 600,    assetClass: 'Agriculture' },
  'CBOT Soybean Oil':           { currency: 'USD', multiplier: 600,    assetClass: 'Agriculture' },
  'Wheat Micro':                { currency: 'USD', multiplier: 10,     assetClass: 'Agriculture' },
  'Mini-Wheat':                 { currency: 'USD', multiplier: 10,     assetClass: 'Agriculture' },
  'Hard Red Spring Wheat':      { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'Kansas Wheat':               { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'Minneapolis Wheat':          { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'Wheat':                      { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'CBOT Wheat':                 { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'Oats':                       { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'RoughRice':                  { currency: 'USD', multiplier: 2000,   assetClass: 'Agriculture' },
  'RapeSeed':                   { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'MillingWheat':               { currency: 'USD', multiplier: 50,     assetClass: 'Agriculture' },
  'WCE Canola':                 { currency: 'CAD', multiplier: 20,     assetClass: 'Agriculture' },
  'ICE Canola':                 { currency: 'CAD', multiplier: 20,     assetClass: 'Agriculture' },

  // ── Livestock ─────────────────────────────────────────────────────────────
  'LIVE CATTLE':                { currency: 'USD', multiplier: 400,    assetClass: 'Livestock' },
  'CME Live Cattle':            { currency: 'USD', multiplier: 400,    assetClass: 'Livestock' },
  'FEEDER CATTLE':              { currency: 'USD', multiplier: 500,    assetClass: 'Livestock' },
  'CME Feeder Cattle':          { currency: 'USD', multiplier: 500,    assetClass: 'Livestock' },
  'LEAN HOG':                   { currency: 'USD', multiplier: 400,    assetClass: 'Livestock' },
  'LEAN HOGS':                  { currency: 'USD', multiplier: 400,    assetClass: 'Livestock' },
  'CME Lean Hogs':              { currency: 'USD', multiplier: 400,    assetClass: 'Livestock' },
  'PORK CUTOUT':                { currency: 'USD', multiplier: 400,    assetClass: 'Livestock' },

  // ── Softs (NYBOT / ICE) ───────────────────────────────────────────────────
  'NYBOT Cocoa':                { currency: 'USD', multiplier: 10,     assetClass: 'Softs' },
  'ICE Cocoa':                  { currency: 'USD', multiplier: 10,     assetClass: 'Softs' },
  'NYBOT Coffee':               { currency: 'USD', multiplier: 375,    assetClass: 'Softs' },
  'NYBOT Coffee C':             { currency: 'USD', multiplier: 375,    assetClass: 'Softs' },
  'ICE Coffee C':               { currency: 'USD', multiplier: 375,    assetClass: 'Softs' },
  'COFFEE 409':                 { currency: 'USD', multiplier: 10,     assetClass: 'Softs' },
  'NYBOT Cotton':               { currency: 'USD', multiplier: 500,    assetClass: 'Softs' },
  'ICE Cotton':                 { currency: 'USD', multiplier: 500,    assetClass: 'Softs' },
  'NYBOT Sugar No 11':          { currency: 'USD', multiplier: 1120,   assetClass: 'Softs' },
  'NYBOT Sugar No.11':          { currency: 'USD', multiplier: 1120,   assetClass: 'Softs' },
  'ICE Sugar No.11':            { currency: 'USD', multiplier: 1120,   assetClass: 'Softs' },
  'Sugar':                      { currency: 'USD', multiplier: 50,     assetClass: 'Softs' },
  'NYBOT FCOJ':                 { currency: 'USD', multiplier: 150,    assetClass: 'Softs' },
  'NYBOT Orange Juice':         { currency: 'USD', multiplier: 150,    assetClass: 'Softs' },

  // ── Dairy ─────────────────────────────────────────────────────────────────
  'Class III Milk':             { currency: 'USD', multiplier: 200,    assetClass: 'Agriculture' },
  'Class IV Milk':              { currency: 'USD', multiplier: 200,    assetClass: 'Agriculture' },
  'Cheese Futures':             { currency: 'USD', multiplier: 200,    assetClass: 'Agriculture' },
  'Butter Futures':             { currency: 'USD', multiplier: 200,    assetClass: 'Agriculture' },
  'Dry Whey':                   { currency: 'USD', multiplier: 440,    assetClass: 'Agriculture' },
  'Nonfat Dry Milk':            { currency: 'USD', multiplier: 440,    assetClass: 'Agriculture' },

  // ── Eurex Index ───────────────────────────────────────────────────────────
  'FDXM':                       { currency: 'EUR', multiplier: 5,      assetClass: 'Equity Index' },
  'FDXS':                       { currency: 'EUR', multiplier: 1,      assetClass: 'Equity Index' },
  'FDAX':                       { currency: 'EUR', multiplier: 25,     assetClass: 'Equity Index' },
  'FESX':                       { currency: 'EUR', multiplier: 10,     assetClass: 'Equity Index' },
  'EURO STOXX 50':              { currency: 'EUR', multiplier: 10,     assetClass: 'Equity Index' },
  'EUREX Euro Stoxx 50':        { currency: 'EUR', multiplier: 10,     assetClass: 'Equity Index' },
  'DAX':                        { currency: 'EUR', multiplier: 25,     assetClass: 'Equity Index' },
  'EUREX DAX':                  { currency: 'EUR', multiplier: 25,     assetClass: 'Equity Index' },
  'FSMI':                       { currency: 'CHF', multiplier: 10,     assetClass: 'Equity Index' },
  'FVS':                        { currency: 'EUR', multiplier: 1000,   assetClass: 'Equity Index' },
  'FATX':                       { currency: 'EUR', multiplier: 10,     assetClass: 'Equity Index' },
  'FFOX':                       { currency: 'EUR', multiplier: 100,    assetClass: 'Equity Index' },
  'FRDX':                       { currency: 'EUR', multiplier: 5,      assetClass: 'Equity Index' },
  'FTDX':                       { currency: 'EUR', multiplier: 10,     assetClass: 'Equity Index' },
  'FSDX':                       { currency: 'EUR', multiplier: 10,     assetClass: 'Equity Index' },

  // ── Eurex Bonds ───────────────────────────────────────────────────────────
  'FGBL':                       { currency: 'EUR', multiplier: 1000,   assetClass: 'Rates' },
  'FGBM':                       { currency: 'EUR', multiplier: 1000,   assetClass: 'Rates' },
  'FGBS':                       { currency: 'EUR', multiplier: 1000,   assetClass: 'Rates' },
  'FGBX':                       { currency: 'EUR', multiplier: 1000,   assetClass: 'Rates' },
  'FOAT':                       { currency: 'EUR', multiplier: 1000,   assetClass: 'Rates' },
  'FBTP':                       { currency: 'EUR', multiplier: 1000,   assetClass: 'Rates' },
  'FBTS':                       { currency: 'EUR', multiplier: 1000,   assetClass: 'Rates' },
  'CONF':                       { currency: 'CHF', multiplier: 1000,   assetClass: 'Rates' },

  // ── Euronext ──────────────────────────────────────────────────────────────
  'CAC40-MINI':                 { currency: 'EUR', multiplier: 1,      assetClass: 'Equity Index' },
  'CAC40':                      { currency: 'EUR', multiplier: 10,     assetClass: 'Equity Index' },
  'CAC 40':                     { currency: 'EUR', multiplier: 10,     assetClass: 'Equity Index' },
  'AEX-MINI':                   { currency: 'EUR', multiplier: 20,     assetClass: 'Equity Index' },
  'AEX':                        { currency: 'EUR', multiplier: 200,    assetClass: 'Equity Index' },
  'BEL20':                      { currency: 'EUR', multiplier: 5,      assetClass: 'Equity Index' },

  // ── ICE Liffe / UK ────────────────────────────────────────────────────────
  'FTSE 100':                   { currency: 'GBP', multiplier: 10,     assetClass: 'Equity Index' },
  'ICE FTSE 100':               { currency: 'GBP', multiplier: 10,     assetClass: 'Equity Index' },
  'FTSE 250':                   { currency: 'GBP', multiplier: 10,     assetClass: 'Equity Index' },
  'GILT MEDIUM':                { currency: 'GBP', multiplier: 1000,   assetClass: 'Rates' },
  'GILT SHORT':                 { currency: 'GBP', multiplier: 1000,   assetClass: 'Rates' },
  'GILT ULTRA':                 { currency: 'GBP', multiplier: 1000,   assetClass: 'Rates' },

  // ── MEFF ──────────────────────────────────────────────────────────────────
  'IBX':                        { currency: 'EUR', multiplier: 10,     assetClass: 'Equity Index' },
  'Mini IBX':                   { currency: 'EUR', multiplier: 1,      assetClass: 'Equity Index' },

  // ── VIX ───────────────────────────────────────────────────────────────────
  'Mini VIX':                   { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'VXM':                        { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'CBOE VIX':                   { currency: 'USD', multiplier: 1000,   assetClass: 'Equity Index' },
  'VIX Futures':                { currency: 'USD', multiplier: 1000,   assetClass: 'Equity Index' },
  'ICE FANG':                   { currency: 'USD', multiplier: 10,     assetClass: 'Equity Index' },

  // ── CME Sector Select ─────────────────────────────────────────────────────
  'E-mini Consumer Disc':       { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'E-mini Consumer Stap':       { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'E-mini Energy Select':       { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'E-mini Financial':           { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'E-mini Health':              { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'E-mini Industrial':          { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'E-mini Materials':           { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'E-mini Nasdaq Biotech':      { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'E-mini Real Estate':         { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'E-mini Technology':          { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'E-mini Utilities':           { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'GOLDMAN SACHS':              { currency: 'USD', multiplier: 250,    assetClass: 'Equity Index' },
  'DOW Real Estate':            { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },

  // ── ICE MSCI ──────────────────────────────────────────────────────────────
  'Mini MSCI World':            { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MSCI World NTR':             { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'Mini MSCI EAFE':             { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MSCI EAFE':                  { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'Mini MSCI Emerging':         { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MSCI Emerging':              { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'Mini MSCI Europe':           { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MSCI Europe NTR':            { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MSCI ACWI':                  { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MSCI Japan':                 { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MSCI India':                 { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'MSCI USA Small':             { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },

  // ── Asian Futures ─────────────────────────────────────────────────────────
  'NIKKEI Micro JPY':           { currency: 'JPY', multiplier: 50,     assetClass: 'Equity Index' },
  'NIKKEI Micro':               { currency: 'USD', multiplier: 0.5,    assetClass: 'Equity Index' },
  'NIKKEI YEN':                 { currency: 'JPY', multiplier: 500,    assetClass: 'Equity Index' },
  'NIKKEI(YEN)':                { currency: 'JPY', multiplier: 500,    assetClass: 'Equity Index' },
  'NIY':                        { currency: 'JPY', multiplier: 500,    assetClass: 'Equity Index' },
  'NIKKEI':                     { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },
  'SGX FTSE China A50':         { currency: 'USD', multiplier: 1,      assetClass: 'Equity Index' },
  'HKFE HSI':                   { currency: 'HKD', multiplier: 50,     assetClass: 'Equity Index' },
  'HSI':                        { currency: 'HKD', multiplier: 50,     assetClass: 'Equity Index' },
  'HKFE MINI HSI':              { currency: 'HKD', multiplier: 10,     assetClass: 'Equity Index' },
  'HKFE MINI HHI':              { currency: 'HKD', multiplier: 10,     assetClass: 'Equity Index' },
  'HKFE HS TECH':               { currency: 'HKD', multiplier: 50,     assetClass: 'Equity Index' },
  'HS TECH':                    { currency: 'HKD', multiplier: 50,     assetClass: 'Equity Index' },
  'HKFE HHI':                   { currency: 'HKD', multiplier: 50,     assetClass: 'Equity Index' },
  'NSE GIFT BANKNIFTY':         { currency: 'USD', multiplier: 20,     assetClass: 'Equity Index' },
  'NSE GIFT NIFTY Financial':   { currency: 'USD', multiplier: 20,     assetClass: 'Equity Index' },
  'NSE GIFT NIFTY IT':          { currency: 'USD', multiplier: 20,     assetClass: 'Equity Index' },
  'NSE GIFT NIFTY':             { currency: 'USD', multiplier: 2,      assetClass: 'Equity Index' },
  'SPI 200':                    { currency: 'AUD', multiplier: 25,     assetClass: 'Equity Index' },
  'ASX SPI':                    { currency: 'AUD', multiplier: 25,     assetClass: 'Equity Index' },
  'TOPIX':                      { currency: 'JPY', multiplier: 10000,  assetClass: 'Equity Index' },
  'SGX Nikkei 225':             { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },
  'SGX MSCI Singapore':         { currency: 'SGD', multiplier: 200,    assetClass: 'Equity Index' },
  'SGX FTSE Taiwan':            { currency: 'USD', multiplier: 40,     assetClass: 'Equity Index' },
  'SGX FTSE China H50':         { currency: 'USD', multiplier: 50,     assetClass: 'Equity Index' },
  'SGX FTSE Vietnam':           { currency: 'USD', multiplier: 5,      assetClass: 'Equity Index' },
  'SGX FTSE Indonesia':         { currency: 'USD', multiplier: 2,      assetClass: 'Equity Index' },
  'SGX FTSE Thailand':          { currency: 'USD', multiplier: 2,      assetClass: 'Equity Index' },
  'HKFE MSCI TAIWAN':           { currency: 'USD', multiplier: 100,    assetClass: 'Equity Index' },
  'Bovespa Mini':               { currency: 'BRL', multiplier: 0.2,    assetClass: 'Equity Index' },
  'BMF Ibovespa Mini':          { currency: 'BRL', multiplier: 0.2,    assetClass: 'Equity Index' },
  'BMF Ibovespa':               { currency: 'BRL', multiplier: 1,      assetClass: 'Equity Index' },

  // ── OSE / TOCOM ───────────────────────────────────────────────────────────
  'OSE 10 JGB':                 { currency: 'JPY', multiplier: 1000000, assetClass: 'Rates' },
  '10 year JGB':                { currency: 'JPY', multiplier: 1000000, assetClass: 'Rates' },
  'OSE Mini JGB':               { currency: 'JPY', multiplier: 100000,  assetClass: 'Rates' },
  'OSE Mini TOPIX':             { currency: 'JPY', multiplier: 1000,    assetClass: 'Equity Index' },
  'OSE Nikkei 225 Micro':       { currency: 'JPY', multiplier: 100,     assetClass: 'Equity Index' },
  'OSE Nikkei 225 Mini':        { currency: 'JPY', multiplier: 1000,    assetClass: 'Equity Index' },
  'OSE Nikkei 225':             { currency: 'JPY', multiplier: 10000,   assetClass: 'Equity Index' },
  'OSE Gold Standard':          { currency: 'JPY', multiplier: 1000,    assetClass: 'Metals' },
  'OSE GOLD':                   { currency: 'JPY', multiplier: 1000,    assetClass: 'Metals' },
  'OSE GOLD mini':              { currency: 'JPY', multiplier: 100,     assetClass: 'Metals' },
  'OSE Platinum Standard':      { currency: 'JPY', multiplier: 500,     assetClass: 'Metals' },
  'OSE Platinum mini':          { currency: 'JPY', multiplier: 50,      assetClass: 'Metals' },
  'OSE Silver':                 { currency: 'JPY', multiplier: 10000,   assetClass: 'Metals' },
  'OSE JPX 400':                { currency: 'JPY', multiplier: 100,     assetClass: 'Equity Index' },
  'TOCOM Gasoline':             { currency: 'JPY', multiplier: 50,      assetClass: 'Energy' },
  'TOCOM Kerosene':             { currency: 'JPY', multiplier: 50,      assetClass: 'Energy' },
  'TOCOM Gas Oil':              { currency: 'JPY', multiplier: 50,      assetClass: 'Energy' },

  // ── LME ───────────────────────────────────────────────────────────────────
  'LME ALUMINIUM ALLOY':        { currency: 'USD', multiplier: 20,     assetClass: 'Metals' },
  'LME ALUMINIUM':              { currency: 'USD', multiplier: 25,     assetClass: 'Metals' },
  'LME COPPER':                 { currency: 'USD', multiplier: 25,     assetClass: 'Metals' },
  'LME ZINC':                   { currency: 'USD', multiplier: 25,     assetClass: 'Metals' },
  'LME NICKEL':                 { currency: 'USD', multiplier: 6,      assetClass: 'Metals' },
  'LME TIN':                    { currency: 'USD', multiplier: 5,      assetClass: 'Metals' },
  'LME LEAD':                   { currency: 'USD', multiplier: 25,     assetClass: 'Metals' },
  'LME NASAAC':                 { currency: 'USD', multiplier: 20,     assetClass: 'Metals' },
  'LME STEEL HRC N':            { currency: 'USD', multiplier: 20,     assetClass: 'Metals' },
  'LME STEEL HRC FOB':          { currency: 'USD', multiplier: 20,     assetClass: 'Metals' },
  'LME STEEL REBAR':            { currency: 'USD', multiplier: 20,     assetClass: 'Metals' },
  'LME STEEL SCRAP':            { currency: 'USD', multiplier: 20,     assetClass: 'Metals' },
  'HKFE LONDON ALUMINIUM':      { currency: 'USD', multiplier: 5,      assetClass: 'Metals' },
  'HKFE LONDON COPPER':         { currency: 'USD', multiplier: 5,      assetClass: 'Metals' },
  'HKFE LONDON ZINC':           { currency: 'USD', multiplier: 5,      assetClass: 'Metals' },

  // ── Montreal / TSX ────────────────────────────────────────────────────────
  'CGB':                        { currency: 'CAD', multiplier: 1000,   assetClass: 'Rates' },
  'CGF':                        { currency: 'CAD', multiplier: 1000,   assetClass: 'Rates' },
  'CGZ':                        { currency: 'CAD', multiplier: 2000,   assetClass: 'Rates' },
  'LGB':                        { currency: 'CAD', multiplier: 1000,   assetClass: 'Rates' },
  'BAX':                        { currency: 'CAD', multiplier: 2500,   assetClass: 'Rates' },
  'SXF':                        { currency: 'CAD', multiplier: 200,    assetClass: 'Equity Index' },

  // ── ASX Bonds ─────────────────────────────────────────────────────────────
  'ASX 10 Bond':                { currency: 'AUD', multiplier: 9590,   assetClass: 'Rates' },
  'ASX 3 Bond':                 { currency: 'AUD', multiplier: 2800,   assetClass: 'Rates' },
  'ASX 5 Bond':                 { currency: 'AUD', multiplier: 4700,   assetClass: 'Rates' },
  'ASX 20 Bond':                { currency: 'AUD', multiplier: 9590,   assetClass: 'Rates' },
  'ASX 90 Bank Bill':           { currency: 'AUD', multiplier: 2466,   assetClass: 'Rates' },
  'ASX 30 Bank Bill':           { currency: 'AUD', multiplier: 822,    assetClass: 'Rates' },

  // ── SGX FX ────────────────────────────────────────────────────────────────
  'SGX INR/USD':                { currency: 'USD', multiplier: 200,    assetClass: 'FX' },
  'SGX BRL/USD':                { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
  'SGX USD/CNH':                { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
  'HKFE USD/CNH':               { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
  'BMF US Dollar':              { currency: 'BRL', multiplier: 50,     assetClass: 'FX' },

  // ── SGX Commodities ───────────────────────────────────────────────────────
  'SGX Iron Ore':               { currency: 'USD', multiplier: 100,    assetClass: 'Metals' },
  'SGX TSI Iron':               { currency: 'USD', multiplier: 100,    assetClass: 'Metals' },

  // ── Other / Misc ──────────────────────────────────────────────────────────
  'Lumber':                     { currency: 'USD', multiplier: 11,     assetClass: 'Other' },
  'LBR':                        { currency: 'USD', multiplier: 11,     assetClass: 'Other' },
  'Uranium':                    { currency: 'USD', multiplier: 250,    assetClass: 'Other' },
  'Iron Ore':                   { currency: 'USD', multiplier: 500,    assetClass: 'Metals' },
  'Bloomberg Commodity':        { currency: 'USD', multiplier: 100,    assetClass: 'Other' },

  // ── DGCX ──────────────────────────────────────────────────────────────────
  'DGCX Gold':                  { currency: 'USD', multiplier: 32.15,  assetClass: 'Metals' },
  'DGCX WTI':                   { currency: 'USD', multiplier: 1000,   assetClass: 'Energy' },
  'DGCX Crude':                 { currency: 'USD', multiplier: 1000,   assetClass: 'Energy' },
  'DGCX Brent':                 { currency: 'USD', multiplier: 1000,   assetClass: 'Energy' },
  'DGCX Silver':                { currency: 'USD', multiplier: 1000,   assetClass: 'Metals' },
  'DGCX Copper':                { currency: 'USD', multiplier: 25000,  assetClass: 'Metals' },
  'DGCX EUR':                   { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
  'DGCX Euro':                  { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
  'DGCX GBP':                   { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
  'DGCX Sterling':              { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
  'DGCX JPY':                   { currency: 'USD', multiplier: 1000,   assetClass: 'FX' },
  'DGCX Japanese':              { currency: 'USD', multiplier: 1000,   assetClass: 'FX' },
  'DGCX Indian Rupee':          { currency: 'USD', multiplier: 200,    assetClass: 'FX' },
  'DGCX AUD':                   { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
  'DGCX CAD':                   { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
  'DGCX CHF':                   { currency: 'USD', multiplier: 100000, assetClass: 'FX' },
};

// Lookup by base product name — user config takes priority over built-in defaults
function getContractSpec(baseProduct) {
  // 1. User-saved override (from Settings tab)
  try {
    const userCfg = JSON.parse(localStorage.getItem('ta_product_config') || '{}');
    if (userCfg[baseProduct]) return userCfg[baseProduct];
  } catch {}

  // 2. Exact match in built-in table
  if (CONTRACT_SPECS[baseProduct]) return CONTRACT_SPECS[baseProduct];

  // 3. Fuzzy match — key must be at least 6 chars to avoid spurious short matches
  const lower = baseProduct.toLowerCase();
  for (const [key, spec] of Object.entries(CONTRACT_SPECS)) {
    if (key.length < 6) continue;
    if (lower.includes(key.toLowerCase()) || key.toLowerCase().includes(lower)) {
      return spec;
    }
  }

  // 4. Fallback — unknown product
  return { currency: 'USD', multiplier: 1, assetClass: 'Other' };
}

// Known strategies (pre-populated for autocomplete; grows via tagging)
const KNOWN_STRATEGIES = [
  'Energy Settle Fade',
  'Breaking News',
  'Financial Figure',
];
